### ISSUE TITLE
x axis overflow issue

### ISSUE THREAD

**Issue by xplosionmind** [francescotonini/francescotonini.github.io#2]
In [this page](https://www.tonini.dev/ubuntu-20-04-hyperv/) there is an horizontal scroll issue.

I suggest fixing it in CSS by adding `overflow-x: hidden;` to the body.

**Comment by francescotonini** [comment]
Hi! Thanks for the feedback. Fortunately the developer of the base theme [fixed it already](https://github.com/dillonzq/LoveIt/pull/280), so I just had to update the submodule.
